/**
 * @devforge/multi-agent — Coder agent (DF-022).
 *
 * Generates implementation. Delegates code generation to an injectable
 * backend; the default backend produces a deterministic implementation
 * placeholder for the task's target path.
 */

import type { AgentContext } from '../context.js';
import type { Artifact, Task } from '../types.js';
import type { AgentBackend, AgentOutput, RoleAgent } from './agent.js';
import { okOutput } from './agent.js';

/** Default backend: produce a deterministic implementation file. */
export async function defaultCoderBackend(task: Task): Promise<AgentOutput> {
  const path = task.target ?? `src/${slug(task.title)}.ts`;
  const artifact: Artifact = {
    path,
    kind: 'FILE',
    content: `/* implementation for ${task.id} */\nexport function ${fnName(task.title)}() {\n  // generated by CODER\n}\n`,
    id: `${task.id}:impl`,
  };
  return okOutput(
    [artifact],
    [`implemented ${path} for ${task.id}`],
  );
}

/** Slugify a title into a path-safe string. */
export function slug(title: string): string {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || 'code';
}

/** Derive a camelCase function name from a title. */
export function fnName(title: string): string {
  const cleaned = title.replace(/[^a-zA-Z0-9 ]/g, '')
    .split(/\s+/)
    .filter(Boolean)
    .map((word, i) => (i === 0 ? word.toLowerCase() : word.charAt(0).toUpperCase() + word.slice(1).toLowerCase()))
    .join('');
  return cleaned || 'implementation';
}

/** Create a coder agent around an optional backend. */
export function createCoderAgent(backend?: AgentBackend): RoleAgent {
  const impl = backend ?? defaultCoderBackend;
  return {
    role: 'CODER',
    async run(task: Task, ctx: AgentContext) {
      const output = await impl(task, ctx);
      return {
        taskId: task.id,
        role: task.role,
        kind: task.kind,
        ok: output.ok,
        status: output.ok ? 'SUCCEEDED' : 'FAILED',
        artifacts: output.artifacts,
        messages: output.messages,
        attempts: 1,
        durationMs: 0,
        error: output.error ?? null,
      };
    },
  };
}
